name: surreal-orm

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C debuginfo=0"
  SCCACHE_DIR: "/home/runner/.cache/sccache"

jobs:
  check_and_test_rust_monorepo:
    name: Run code checks for Rust workspace
    timeout-minutes: 80
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android /opt/ghc
          sudo rm -rf /usr/share/dotnet /usr/local/.ghcup
          docker system prune -a -f

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install sccache
        run: |
          cargo install sccache || echo "sccache already installed"
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            /home/runner/.cache/sccache
          key: rust-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Clean previous builds
        run: cargo clean

      - name: Run cargo test per workspace package
        run: |
          for package in $(cargo metadata --format-version 1 --no-deps | jq -r '.packages[].name'); do
            echo "Running tests for $package"
            cargo test -p "$package" --release -- --test-threads=1
          done

  clippy:
    name: Clippy Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: make check
